[proxmox]
pveha1.internal ansible_host=192.168.10.11
pveha2.internal ansible_host=192.168.10.12

[backup]
pveha-sto.internal ansible_host=192.168.10.20 ansible_user=pi

[proxmox:vars]
ansible_user=root